### ISSUE TITLE
Link Error on homepage re: IRC

### ISSUE THREAD

**Issue by iandioch** [KevinWorkman/StaticVoidGames#12]
The link on the homepage report "Kevin's latest blog: IRC Client" goes to dud URL http://staticvoidgames.%3Chr/%3E%3Cp%3ERead%20more%20%3Ca%20href=

The text is "Thanks to [here].", where [here] is the link.

Don't know if it's just a missing quote or something, or if the website has been compromised by a team of sophisticated monkeys on internet-connected typewriters. 

My money's on the latter.

**Comment by KevinWorkman** [comment]
The current frontpage just shows the entire text of the blog, so I'm going to close this issue.
